name: caller
on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  job_2:
    uses: saru1604/reuseableworkflowcall/.github/workflows/workflow1.yml@main
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
    secrets:
    
      registry_username: abc
      registry_password: abc123      
#       registry_username: ${{secrets.REGISTRY_USERNAME}}
#       registry_password: ${{secrets.REGISTRY_PASSWORD}}
